travis:
  secure:
    BINSTAR_TOKEN: uElRZymKHNKhFDKQ/Uu3QVeMoReic/Vi0Az+6cdRYgXFWCOtmprrdWNYNbBo7MKBLROpFd05bxV4C09yg1usTV2GaiFmMvRgV1vMzThWqDdTL6Br5ZPy348DX3ufHX640oBfEDBqFL15CQm/o4SiLhM15kB3svLNR12MKlbJc0PemZtyv9hM/l3Yozm5uHAnavwQpiK4rW0UGJ2zyB+r0CQH6cAkJwhVCzhfn5XfRQEOQSXn47LEA91h/VsexpERcGgUJMoAJq25DcYfgjdFdcBmLRNDHWncgXhPWGWrm0Tq76TPYOEsJcfGbDIn6U3xvaFuDPOV1m//v5cpP7DvgWytq+OGdHA/ebgHHEKHYqg3xEcyTzv+Xuj64LaTbIkqyIYu5cyAH3uU6Z2WZfqOOTlLHeTodmMWUON5FtEBBSFeUbauTgTE3/b7ddsQhlvch4D1lIf8+V9pcoNYqScuw8JjGAhmdvXzMWk10qux7nb7sNDcSYqiXM6dmHrSipDFzG40azeaOfioRnguFvKSkVTZj4DzV97FOZh5+jzlcR0No4d4z+fr0wzcVvC2RJIfNr0WDaNvRtGzxTQkNX5Wn58PWvseX5XnJFHho1fhMB786aFXOKsEiN2mw40W8dKy8pBo9W1sJ8ZgTJzZHdvTDVGPG9PMwoLJbIYs10EIixM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
